main: cn.plixe.waitbeforerespawn.Main
name: WaitBeforeRespawn
author: Plixe
api-version: 1.13
version: 1.2

permissions:
   wbr.admin:
      default: false
      description: All permissions.
      children:
         - wbr.bypass
         - wbr.help
         - wbr.reload
         - wbr.tproom
         - wbr.setroom
   wbr.mod:
      default: false
      description: Waiting-room permissions.
      children:
         - wbr.help
         - wbr.tproom
         - wbr.setroom
   wbr.bypass:
      default: false
      description: Bypass waiting time.
   wbr.help:
      default: op
      description: Allow to show help message.
   wbr.reload:
      default: op
      description: Allow to reload configurations files.
   wbr.tproom:
      default: op
      description: Allow player to teleport at the waiting-room.
   wbr.setroom:
      default: op
      description: Allow player to set the waiting-room location.
      
commands:
   wbr:
      description: Plugin's main command.